networks:
  ascue:
    driver: bridge

services:
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - ascue
    restart: always

  nest-app:
    build:
      context: .
    container_name: nest-app
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - ascue
    restart: always